### PR TITLE
Specify column types of exceptions seed

### LINKED ISSUE #193: Rules models all fail since upgrading to 0.1.2 (Postgres)
### Steps to reproduce
Upgrade to 0.1.2
Run with `dbt build --select package:dbt_project_evaluator --vars 'evaluator: true'`
I have also tried adding an exception seed with an example but no luck.

### Expected results
Rules models should run without error (actual behavior with 0.1.2)

### Actual results
All rules model fail with the same Database error, example below

### Screenshots and log output
Example : 
```
16:15:35  Database Error in model fct_model_naming_conventions (models/marts/structure/fct_model_naming_conventions.sql)
16:15:35    invalid input syntax for type integer: "fct_model_naming_conventions"
16:15:35    LINE 8: where fct_name = 'fct_model_naming_conventions'
```

### System information
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/dbt_project_evaluator
    version: 0.1.2

**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.0
  - latest:    1.2.0 - Up to date!

Plugins:
  - redshift: 1.2.0 - Up to date!
  - postgres: 1.2.0 - Up to date!
```

### PR DESCRIPTION
**Pull request by graciegoheen**
This is a:
- [x] bug fix PR with no breaking changes
- [ ] new functionality

## Link to Issue 

Closed #193 

## Description & motivation

- Specify column types for exceptions seed to resolve error on `where` clause

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Review by dave-connors-3 — APPROVED** [review]
🦞 LGTM
(lobster gets the mayo [to make a lobster roll])

**Comment by b-per** [comment]
It doesn't work unfortunately. I think it is related to other discussions I saw recently about the fact that empty strings in seeds are considered `NULL` in dbt (and not casted to `string/varchar`).

**Comment by b-per** [comment]
I feel like defining the seed format in the `yml` file and making it compatible cross DW is the way to go

**Comment by b-per** [comment]
🥐 LGTM now with #195 passing!

**Review by b-per — APPROVED** [review]

**Pull request merged**
