### PR TITLE
Fix `base_source_columns` and `base_node_columns` in Redshift

### LINKED ISSUE #463: Initial build fails with column size errors
### Describe the bug
When running `dbt build --select package:dbt_project_evaluator`, I get a few errors when the package tries to run staging models related to column size.

### Steps to reproduce
This is currently what is in my dbt_project.yml:

```
  dbt_project_evaluator:
    +enabled: "{{ env_var('ENABLE_DBT_PROJECT_EVALUATOR', 'true') | lower == 'true' | as_bool }}"
    +tags: "Analytics Engineering"
    +meta:
      +owner: "Analytics Engineering"
    marts:
      core:
        enabled: true
      dag:
        enabled: false
        fct_direct_join_to_source:
          +enabled: false
        fct_model_fanout:
          +enabled: false
        fct_multiple_sources_joined:
          +enabled: false
        fct_source_fanout:
          +enabled: false
        fct_staging_dependent_on_staging:
          +enabled: false
      documentation:
        fct_documentation_coverage:
          +enabled: true
        fct_undocumented_models:
          +enabled: true
      performance:
        enabled: false
      structure:
        enabled: false
        fct_model_directories:
          +enabled: false
        fct_model_naming_conventions:
          +enabled: false
      tests:
        enabled: false
        fct_missing_primary_key_tests:
          +enabled: false
        fct_test_coverage:
          +enabled: false
      dispatch:
        - macro_namespace: dbt
          search_order: ['dbt_project_evaluator', 'dbt']
```
I also have a few lines disabling the package's seed file (to use my own) and enabling tests.

### Expected results
All models run.

### Actual results
Models do not run.

### Screenshots and log output
Screenshot 2024-06-11 at 12 53 05 PM

### System information
**The contents of your `packages.yml` file:**
```
  - package: dbt-labs/dbt_project_evaluator
    version: 0.6.0
```
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.8.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 1.3.7 - Update available!
  - redshift: 1.3.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Are you interested in contributing the fix?
No

### LINKED ISSUE #465: Error in `base_source_columns`
### Describe the bug

When running the model `base_source_columns` by `dbt run`, I encounter below error
image

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.8.1
```

### Additional context

The problem locates on the `post-hook` parameter in the model, since the query to create table still can be run in Snowflake. Probably, the post-hook query is trying to insert more columns than the ones existing in the output object
image

### LINKED ISSUE #466: Error in `base_source_columns` and `base_node_columns` in Redshift
### Describe the bug

- Errors in `base_source_columns` and `base_node_columns` in Redshift:
```
(dbt-env-1.8) (dbt-env-1.6) stevengonzalez@Steven-Gonzalez dbt-campaign-workflows % dbt build -s  base_node_columns base_source_columns
17:08:11  Running with dbt=1.8.3
17:08:12  [WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
information.
17:08:12  Registered adapter: redshift=1.8.1
17:08:18  Found 734 models, 34 snapshots, 83 seeds, 3215 data tests, 1137 sources, 1 exposure, 1801 macros
17:08:19  
17:08:22  Concurrency: 4 threads (target='dev')
17:08:22  
17:08:22  1 of 2 START sql table model sgonzalez.base_node_columns ....................... [RUN]
17:08:22  2 of 2 START sql table model sgonzalez.base_source_columns ..................... [RUN]
17:08:35  1 of 2 ERROR creating sql table model sgonzalez.base_node_columns .............. [ERROR in 13.89s]
17:08:43  2 of 2 ERROR creating sql table model sgonzalez.base_source_columns ............ [ERROR in 21.60s]
17:08:44  
17:08:44  Finished running 2 table models in 0 hours 0 minutes and 24.93 seconds (24.93s).
17:08:45  
17:08:45  Completed with 2 errors and 0 warnings:
17:08:45  
17:08:45    Database Error in model base_node_columns (models/staging/graph/base/base_node_columns.sql)
  value too long for type character varying(1)
  compiled Code at target/run/dbt_project_evaluator/models/staging/graph/base/base_node_columns.sql
17:08:45  
17:08:45    Database Error in model base_source_columns (models/staging/graph/base/base_source_columns.sql)
  INSERT has more expressions than target columns
  compiled Code at target/run/dbt_project_evaluator/models/staging/graph/base/base_source_columns.sql
  ```
### Steps to reproduce

- Running on dbt-core/dbt-redshift v1.8.0 with dbt-project-evaluator `0.12.0`

### Expected results

- Get Models to run and insert data via `post-hook`

### Actual results

- N/A

### System information
**The contents of your `packages.yml` file:**
```

packages:
  - package: dbt-labs/audit_helper
    version: 0.12.0
  - package: dbt-labs/dbt_utils
    version: 1.2.0
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: calogica/dbt_expectations
    version: 0.10.3
  - package: elementary-data/elementary
    version: 0.15.2
  - package: dbt-labs/redshift
    version: 0.9.0  
  - package: data-mie/dbt_profiler
    version: 0.8.2
  - package: dbt-labs/dbt_project_evaluator
    version: 0.12.0packages:
  - package: dbt-labs/audit_helper
    version: 0.12.0
  - package: dbt-labs/dbt_utils
    version: 1.2.0
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: calogica/dbt_expectations
    version: 0.10.3
  - package: elementary-data/elementary
    version: 0.15.2
  - package: dbt-labs/redshift
    version: 0.9.0  
  - package: data-mie/dbt_profiler
    version: 0.8.2
  - package: dbt-labs/dbt_project_evaluator
    version: 0.12.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
(dbt-env-1.8) (dbt-env-1.6) stevengonzalez@Steven-Gonzalez dbt-campaign-workflows % dbt --version
Core:
  - installed: 1.8.3
  - latest:    1.8.3 - Up to date!

Plugins:
  - redshift: 1.8.1 - Up to date!
  - postgres: 1.8.2 - Up to date!
```

### Are you interested in contributing the fix?

- Yes! I'll link a PR to this issue with the fix I've employed locally

### PR DESCRIPTION
**Pull request by stevenconnorg**
This is a:
- [x] bug fix PR with no breaking changes
- [ ] new functionality

## Link to Issue 

- Resolves #465 
- Resolves #466 
- Resolves #463 

## Description & motivation

- Fixes the issue I submitted in #466  
  - Use `type_large_string()` in `base_source_columns` and `base_node_columns`
  - Update `redshift__type_large_string` length 
  - Consolidate schemas for base column models to fix `insert` error
 
## Integration Test Screenshot

Screenshot 2024-06-24 at 1 13 07 PM

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [x] Redshift
    - [ ] Snowflake
    - [ ] Databricks
    - [ ] DuckDB
    - [ ] Trino/Starburst
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207541489422495

### CODE REVIEW

**Comment by b-per** [comment]
Hi @stevenconnorg 

Thanks for the work on this one!

At first, I am a bit worried of moving to `varchar(50000)` and changing all the `type_string()` in those models to `type_large_string()` for all users of the package.

From what I read [here](https://medium.com/@alice_thomaz/best-practices-with-amazon-redshift-architecture-organization-and-performance-optimization-1dfcd6512746#:~:text=Using%20data%20types%20with%20a,larger%20memory%20space%20than%20necessary.) , I understand that Redshift does some optimization/memory allocation based on the types and I wouldn't want people who don't have any issue today with Redshift to be negatively impacted by performance following this change.

In your specific case, do you know what specific column(s) was/were creating the issue? And what `varchar` size this column has?

We might then be able to target the changes required to fix the reported issues.

**Comment by stevenconnorg** [comment]
Hey @b-per 

For some reason, `dbt.type_string()` is creating `character varying(1)` column, so this is causing the majority of the issues in these models (also reported in #463) 

However, I'm still running into issues with `redshift__type_large_string()` in the `description` column, with the max string length around ~13k characters.

So maybe we bump the `redshift__type_large_string()` length to 15-20 thousand, and then figure out what's going on with the `dbt.type_string()`?

**Comment by b-per** [comment]
Yes, I think it is better to get to the bottom of it.

Do you have `jq` installed? If not, could you install it and do (I am on Mac, but we could do something similar in Windows)

```
cat target/manifest.json | jq '.macros | .[] | select(.name | contains("type_string"))'
```

and copy the results here?


My results look like 

```
{
  "name": "type_string",
  "resource_type": "macro",
  "package_name": "dbt",
  "path": "macros/utils/data_types.sql",
  "original_file_path": "macros/utils/data_types.sql",
  "unique_id": "macro.dbt.type_string",
  "macro_sql": "\n\n{%- macro type_string() -%}\n  {{ return(adapter.dispatch('type_string', 'dbt')()) }}\n{%- endmacro -%}\n\n",
  "depends_on": {
    "macros": [
      "macro.dbt.default__type_string"
    ]
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719397302.694219,
  "supported_languages": null
}
{
  "name": "default__type_string",
  "resource_type": "macro",
  "package_name": "dbt",
  "path": "macros/utils/data_types.sql",
  "original_file_path": "macros/utils/data_types.sql",
  "unique_id": "macro.dbt.default__type_string",
  "macro_sql": "{% macro default__type_string() %}\n    {{ return(api.Column.translate_type(\"string\")) }}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719397302.694326,
  "supported_languages": null
}
{
  "name": "redshift__type_string",
  "resource_type": "macro",
  "package_name": "dbt_project_evaluator",
  "path": "macros/cross_db_shim/redshift_shims.sql",
  "original_file_path": "macros/cross_db_shim/redshift_shims.sql",
  "unique_id": "macro.dbt_project_evaluator.redshift__type_string",
  "macro_sql": "{%- macro redshift__type_string() -%}\n  {{ \"VARCHAR(600)\" }}\n{%- endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719397302.810622,
  "supported_languages": null
}
```

**Comment by stevenconnorg** [comment]
Hey @b-per , here are the results from the `jq` command:
```
{
  "name": "type_string",
  "resource_type": "macro",
  "package_name": "dbt",
  "path": "macros/utils/data_types.sql",
  "original_file_path": "macros/utils/data_types.sql",
  "unique_id": "macro.dbt.type_string",
  "macro_sql": "\n\n{%- macro type_string() -%}\n  {{ return(adapter.dispatch('type_string', 'dbt')()) }}\n{%- endmacro -%}\n\n",
  "depends_on": {
    "macros": [
      "macro.dbt.default__type_string"
    ]
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348795.668191,
  "supported_languages": null
}
{
  "name": "default__type_string",
  "resource_type": "macro",
  "package_name": "dbt",
  "path": "macros/utils/data_types.sql",
  "original_file_path": "macros/utils/data_types.sql",
  "unique_id": "macro.dbt.default__type_string",
  "macro_sql": "{% macro default__type_string() %}\n    {{ return(api.Column.translate_type(\"string\")) }}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348795.668301,
  "supported_languages": null
}
{
  "name": "type_string",
  "resource_type": "macro",
  "package_name": "dbt_profiler",
  "path": "macros/cross_db_utils.sql",
  "original_file_path": "macros/cross_db_utils.sql",
  "unique_id": "macro.dbt_profiler.type_string",
  "macro_sql": "\n\n{%- macro type_string() -%}\n  {{ return(adapter.dispatch(\"type_string\", macro_namespace=\"dbt_profiler\")()) }}\n{%- endmacro -%}\n\n",
  "depends_on": {
    "macros": [
      "macro.dbt_profiler.default__type_string"
    ]
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348795.795249,
  "supported_languages": null
}
{
  "name": "default__type_string",
  "resource_type": "macro",
  "package_name": "dbt_profiler",
  "path": "macros/cross_db_utils.sql",
  "original_file_path": "macros/cross_db_utils.sql",
  "unique_id": "macro.dbt_profiler.default__type_string",
  "macro_sql": "{%- macro default__type_string() -%}\n  varchar\n{%- endmacro -%}\n\n",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348795.7953038,
  "supported_languages": null
}
{
  "name": "bigquery__type_string",
  "resource_type": "macro",
  "package_name": "dbt_profiler",
  "path": "macros/cross_db_utils.sql",
  "original_file_path": "macros/cross_db_utils.sql",
  "unique_id": "macro.dbt_profiler.bigquery__type_string",
  "macro_sql": "{%- macro bigquery__type_string() -%}\n  string\n{%- endmacro -%}\n\n",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348795.7953548,
  "supported_languages": null
}
{
  "name": "databricks__type_string",
  "resource_type": "macro",
  "package_name": "dbt_profiler",
  "path": "macros/cross_db_utils.sql",
  "original_file_path": "macros/cross_db_utils.sql",
  "unique_id": "macro.dbt_profiler.databricks__type_string",
  "macro_sql": "{%- macro databricks__type_string() -%}\n  string\n{%- endmacro -%}\n\n\n",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348795.795406,
  "supported_languages": null
}
{
  "name": "redshift__type_string",
  "resource_type": "macro",
  "package_name": "dbt_project_evaluator",
  "path": "macros/cross_db_shim/redshift_shims.sql",
  "original_file_path": "macros/cross_db_shim/redshift_shims.sql",
  "unique_id": "macro.dbt_project_evaluator.redshift__type_string",
  "macro_sql": "{%- macro redshift__type_string() -%}\n  {{ \"VARCHAR(600)\" }}\n{%- endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348795.9382882,
  "supported_languages": null
}
{
  "name": "edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.edr_type_string",
  "macro_sql": "\n\n\n{%- macro edr_type_string() -%}\n    {{ return(adapter.dispatch('edr_type_string', 'elementary')()) }}\n{%- endmacro -%}\n\n",
  "depends_on": {
    "macros": [
      "macro.elementary.postgres__edr_type_string"
    ]
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.390201,
  "supported_languages": null
}
{
  "name": "default__edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.default__edr_type_string",
  "macro_sql": "{% macro default__edr_type_string() %}\n    {# Redshift #}\n    {% do return(\"varchar(4096)\") %}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.390293,
  "supported_languages": null
}
{
  "name": "postgres__edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.postgres__edr_type_string",
  "macro_sql": "{% macro postgres__edr_type_string() %}\n    {% if var(\"sync\", false) %}\n        {% do return(\"text\") %}\n    {% else %}\n        {% do return(\"varchar(4096)\") %}\n    {% endif %}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.390466,
  "supported_languages": null
}
{
  "name": "snowflake__edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.snowflake__edr_type_string",
  "macro_sql": "{% macro snowflake__edr_type_string() %}\n    {# Default max varchar size in Snowflake is 16MB #}\n    {% do return(\"varchar\") %}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.3905568,
  "supported_languages": null
}
{
  "name": "bigquery__edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.bigquery__edr_type_string",
  "macro_sql": "{% macro bigquery__edr_type_string() %}\n    {# Default max string size in Bigquery is 65K #}\n    {% do return(\"string\") %}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.390642,
  "supported_languages": null
}
{
  "name": "spark__edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.spark__edr_type_string",
  "macro_sql": "{% macro spark__edr_type_string() %}\n    {% do return(\"string\") %}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.390722,
  "supported_languages": null
}
{
  "name": "athena__edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.athena__edr_type_string",
  "macro_sql": "{% macro athena__edr_type_string() %}\n    {% do return(\"varchar\") %}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.390801,
  "supported_languages": null
}
{
  "name": "trino__edr_type_string",
  "resource_type": "macro",
  "package_name": "elementary",
  "path": "macros/utils/data_types/data_type.sql",
  "original_file_path": "macros/utils/data_types/data_type.sql",
  "unique_id": "macro.elementary.trino__edr_type_string",
  "macro_sql": "{% macro trino__edr_type_string() %}\n    {% do return(\"varchar\") %}\n{% endmacro %}",
  "depends_on": {
    "macros": []
  },
  "description": "",
  "meta": {},
  "docs": {
    "show": true,
    "node_color": null
  },
  "patch_path": null,
  "arguments": [],
  "created_at": 1719348796.390879,
  "supported_languages": null
}
```

**Comment by b-per** [comment]
With #475 implemented and released in the latest version, I think that this is not needed anymore. Let's open a new issue if there is still an issue.

**Pull request closed without merging**
