### PR TITLE
add metrics to int_direct_relationships

### LINKED ISSUE #139: Metrics lineage is not reported
Any reason why we are joining the exposures parents but not the metrics in the code below?

It looks like something I missed (the CTE `direct_metrics_relationships` is created but not used) but I wanted to confirm that this is not something we implemented like this by design.

https://github.com/dbt-labs/dbt-project-evaluator/blob/12b1c2cc531e7ffe48f8040dbed1ad25374fa5a7/models/marts/core/int_direct_relationships.sql#L17-L52

### PR DESCRIPTION
**Pull request by graciegoheen**
This is a:
- [x] bug fix PR with no breaking changes
- [ ] new functionality

## Link to Issue 

Closes #139 

## Description & motivation

Added metrics to `int_direct_relationships`

## Integration Test Screenshot

Screen Shot 2022-06-27 at 11 18 28 AM

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Review by dave-connors-3 — APPROVED** [review]
🦞

**Review by b-per — APPROVED** [review]
🥖 

Doesn't it feel odd though that a bug didn't raise a failing test and that we didn't create a new test that would have failed without the fix?

**Comment by graciegoheen** [comment]
@b-per I suppose we're not really doing anything yet with the metrics, so they don't yet show up in any of the integration tests. I could add a new integration test to check the output of `int_direct_relationships`, `int_all_graph_resources`, and `int_all_dag_relationships` (though the final would be a bit tricky since we can't add arrays into seed files)?

**Comment by b-per** [comment]
My question was kind of rhetorical and I don't know if we should solve it now...
Putting a test on all those models just for this change looks like an overkill

Maybe we will test those later with other use cases

**Pull request merged**
