### PR TITLE
Dispatching macro filter_exceptions

### LINKED ISSUE #212: Make the filter_exceptions macro dispatchable
### Describe the feature
It would be very useful to be able to override the macros in this package. E.g. being able to override the `filter_exceptions` macro so that I can create my own version of it where I e.g. can use regex or similar and not be limited by the [not like](https://github.com/dbt-labs/dbt-project-evaluator/blob/4d9029cd23ba79de95e624ef5c4c3f14850d5cfd/macros/filter_exceptions.sql#L14) filter.

### Describe alternatives you've considered
Only possibilities to override a macro in a package that is not dispatched seems to be forking the repo or doing changes directly in the package itself. See [overriding package macros](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#overriding-package-macros). 

### Additional context
Dispatching the macro will also make it possible to do db specific customization.

### Are you interested in contributing this feature?
I am more than happy to create a PR with suggested changes and you decide if it makes sense or not.

### PR DESCRIPTION
**Pull request by larssnek**
This is a:
- [ ] bug fix PR with no breaking changes
- [x] new functionality

## Link to Issue 

Closes #212 

## Description & motivation

Dispatching the macro `filter_exceptions` in order to be able to override this macro in root projects

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by larssnek** [comment]
@dave-connors-3, this would be very useful for a hackathon we are working on, does it make sense to do it this way?
I'm a Snowflake guy, not Databricks, so not sure if the failing integration tests for Databricks is really related?

**Comment by larssnek** [comment]
Databricks integration tests just needed a retry :raised_hands:

**Comment by b-per** [comment]
Thanks for the PR @larssnek ! This implemetation looks all good to me. Did you try to overwrite the macro locally after those changes and did it work?

I will just have a quick chat with the team about how we want to handle the `CHANGELOG.md` before merging it. This file is actually outdated today and the CHANGELOG is generated automatically after each release on [this page](https://github.com/dbt-labs/dbt-project-evaluator/releases).

**Review by b-per — APPROVED** [review]
Thanks! 

We are just going to get rid of the CHANGELOG file as we are going to be using the semi autogenerated one from the releases page (and update the PR instructions to remove mentions to the CHANGELOG file)

**Pull request merged**
